<?php
/**
 * Gutenberg Block Fields
 */

 if( function_exists('acf_add_local_field_group') ):

 acf_add_local_field_group(array(
 	'key' => 'group_5fa928df03a5c',
 	'title' => 'Communities Nearby',
 	'fields' => array(
 		array(
 			'key' => 'field_5fa9290b74f04',
 			'label' => 'Title',
 			'name' => 'title',
 			'type' => 'text',
 			'instructions' => '',
 			'required' => 0,
 			'conditional_logic' => 0,
 			'wrapper' => array(
 				'width' => '',
 				'class' => '',
 				'id' => '',
 			),
 			'default_value' => 'Communities Near you',
 			'placeholder' => '',
 			'prepend' => '',
 			'append' => '',
 			'maxlength' => '',
 		),
 	),
 	'location' => array(
 		array(
 			array(
 				'param' => 'block',
 				'operator' => '==',
 				'value' => 'acf/communities',
 			),
 		),
 	),
 	'menu_order' => 0,
 	'position' => 'normal',
 	'style' => 'default',
 	'label_placement' => 'top',
 	'instruction_placement' => 'label',
 	'hide_on_screen' => '',
 	'active' => true,
 	'description' => '',
 	'modified' => 1604933492,
 ));

 acf_add_local_field_group(array(
 	'key' => 'group_5fa932fcd1bd1',
 	'title' => 'Communities list',
 	'fields' => array(
 		array(
 			'key' => 'field_5fa9330995826',
 			'label' => 'Title',
 			'name' => 'title',
 			'type' => 'text',
 			'instructions' => '',
 			'required' => 0,
 			'conditional_logic' => 0,
 			'wrapper' => array(
 				'width' => '',
 				'class' => '',
 				'id' => '',
 			),
 			'default_value' => '',
 			'placeholder' => '',
 			'prepend' => '',
 			'append' => '',
 			'maxlength' => '',
 		),
 		array(
 			'key' => 'field_5fa9331495827',
 			'label' => 'Description list',
 			'name' => 'description_list',
 			'type' => 'repeater',
 			'instructions' => '',
 			'required' => 0,
 			'conditional_logic' => 0,
 			'wrapper' => array(
 				'width' => '',
 				'class' => '',
 				'id' => '',
 			),
 			'collapsed' => '',
 			'min' => 0,
 			'max' => 0,
 			'layout' => 'table',
 			'button_label' => '',
 			'sub_fields' => array(
 				array(
 					'key' => 'field_5fa9333095828',
 					'label' => 'Abbreviation',
 					'name' => 'abbreviation',
 					'type' => 'text',
 					'instructions' => '',
 					'required' => 0,
 					'conditional_logic' => 0,
 					'wrapper' => array(
 						'width' => '',
 						'class' => '',
 						'id' => '',
 					),
 					'default_value' => '',
 					'placeholder' => '',
 					'prepend' => '',
 					'append' => '',
 					'maxlength' => '',
 				),
 				array(
 					'key' => 'field_5fa9333d95829',
 					'label' => 'Text',
 					'name' => 'text',
 					'type' => 'text',
 					'instructions' => '',
 					'required' => 0,
 					'conditional_logic' => 0,
 					'wrapper' => array(
 						'width' => '',
 						'class' => '',
 						'id' => '',
 					),
 					'default_value' => '',
 					'placeholder' => '',
 					'prepend' => '',
 					'append' => '',
 					'maxlength' => '',
 				),
 			),
 		),
 		array(
 			'key' => 'field_5fa9334f9582a',
 			'label' => 'Column',
 			'name' => 'column',
 			'type' => 'repeater',
 			'instructions' => '',
 			'required' => 0,
 			'conditional_logic' => 0,
 			'wrapper' => array(
 				'width' => '',
 				'class' => '',
 				'id' => '',
 			),
 			'collapsed' => '',
 			'min' => 0,
 			'max' => 0,
 			'layout' => 'table',
 			'button_label' => 'Add Column',
 			'sub_fields' => array(
 				array(
 					'key' => 'field_5fa9335b9582b',
 					'label' => 'List',
 					'name' => 'list',
 					'type' => 'repeater',
 					'instructions' => '',
 					'required' => 0,
 					'conditional_logic' => 0,
 					'wrapper' => array(
 						'width' => '',
 						'class' => '',
 						'id' => '',
 					),
 					'collapsed' => '',
 					'min' => 0,
 					'max' => 0,
 					'layout' => 'block',
 					'button_label' => 'Add list',
 					'sub_fields' => array(
 						array(
 							'key' => 'field_5fa933919582d',
 							'label' => 'State',
 							'name' => 'state',
 							'type' => 'select',
 							'instructions' => '',
 							'required' => 0,
 							'conditional_logic' => 0,
 							'wrapper' => array(
 								'width' => '',
 								'class' => '',
 								'id' => '',
 							),
 							'choices' => array(
 								'Arizona' => 'Arizona',
 								'Texas' => 'Texas',
 								'Washington' => 'Washington',
 								'Montana' => 'Montana',
 								'California' => 'California',
 								'Idaho' => 'Idaho',
 								'Illinois' => 'Illinois',
 								'Colorado' => 'Colorado',
 							),
 							'default_value' => 'Arizona',
 							'allow_null' => 0,
 							'multiple' => 0,
 							'ui' => 0,
 							'return_format' => 'value',
 							'ajax' => 0,
 							'placeholder' => '',
 						),
 					),
 				),
 			),
 		),
 	),
 	'location' => array(
 		array(
 			array(
 				'param' => 'block',
 				'operator' => '==',
 				'value' => 'acf/communities-list',
 			),
 		),
 	),
 	'menu_order' => 0,
 	'position' => 'normal',
 	'style' => 'default',
 	'label_placement' => 'top',
 	'instruction_placement' => 'label',
 	'hide_on_screen' => '',
 	'active' => true,
 	'description' => '',
 	'modified' => 1604933513,
 ));

 acf_add_local_field_group(array(
 	'key' => 'group_5fc82cf7cc860',
 	'title' => 'Floor Plan Settings',
 	'fields' => array(
 		array(
 			'key' => 'field_5fc82d43a6b17',
 			'label' => 'Choose Floor Plan',
 			'name' => 'floorplan_id',
 			'type' => 'select',
 			'instructions' => 'Choose the floorplan to display.',
 			'required' => 0,
 			'conditional_logic' => 0,
 			'wrapper' => array(
 				'width' => '',
 				'class' => '',
 				'id' => '',
 			),
 			'choices' => array(
 				0 => 'Choose One',
 				1575 => 'Memory Care "P" Style 1 Bed, 1 Bath',
 			),
 			'default_value' => false,
 			'allow_null' => 0,
 			'multiple' => 0,
 			'ui' => 0,
 			'return_format' => 'value',
 			'ajax' => 0,
 			'placeholder' => '',
 		),
 	),
 	'location' => array(
 		array(
 			array(
 				'param' => 'block',
 				'operator' => '==',
 				'value' => 'acf/floorplan',
 			),
 		),
 	),
 	'menu_order' => 0,
 	'position' => 'normal',
 	'style' => 'default',
 	'label_placement' => 'top',
 	'instruction_placement' => 'label',
 	'hide_on_screen' => '',
 	'active' => true,
 	'description' => '',
 ));

 acf_add_local_field_group(array(
 	'key' => 'group_5fa9106b192e2',
 	'title' => 'Toolbar',
 	'fields' => array(
 		array(
 			'key' => 'field_5fa94bee68120',
 			'label' => 'Title',
 			'name' => 'title',
 			'type' => 'text',
 			'instructions' => '',
 			'required' => 0,
 			'conditional_logic' => 0,
 			'wrapper' => array(
 				'width' => '',
 				'class' => '',
 				'id' => '',
 			),
 			'default_value' => '',
 			'placeholder' => '',
 			'prepend' => '',
 			'append' => '',
 			'maxlength' => '',
 		),
 		array(
 			'key' => 'field_5fa94bda6811f',
 			'label' => 'Page for search',
 			'name' => 'page_for_search',
 			'type' => 'page_link',
 			'instructions' => '',
 			'required' => 1,
 			'conditional_logic' => 0,
 			'wrapper' => array(
 				'width' => '',
 				'class' => '',
 				'id' => '',
 			),
 			'post_type' => array(
 				0 => 'page',
 			),
 			'taxonomy' => '',
 			'allow_null' => 0,
 			'allow_archives' => 0,
 			'multiple' => 0,
 		),
 	),
 	'location' => array(
 		array(
 			array(
 				'param' => 'block',
 				'operator' => '==',
 				'value' => 'acf/toolbar',
 			),
 		),
 	),
 	'menu_order' => 0,
 	'position' => 'normal',
 	'style' => 'default',
 	'label_placement' => 'top',
 	'instruction_placement' => 'label',
 	'hide_on_screen' => '',
 	'active' => true,
 	'description' => '',
 	'modified' => 1604933485,
 ));

 endif;
  ?>
